spring:
  datasource:
    driver-class-name: ${DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    url: ${DB_URL}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    show-sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    open-in-view: false

springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    path: /api-docs/json
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: swagger-ui.html
  cache:
    disabled: true
  packages-to-scan: ${PACKAGES_TO_SCAN}
  
jwt: 
  secret: ${TOKEN_SECRET_KEY}
  expiration: ${TOKEN_EXPIRATION}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucketName: ${S3_BUCKETNAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false
